PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `bank_transaction__new` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`first_seen_import_id` text,
	`last_seen_import_id` text,
	`external_transaction_id` text,
	`dedupe_key` text NOT NULL,
	`booking_date` text NOT NULL,
	`value_date` text,
	`amount_cents` integer NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`original_amount_cents` integer,
	`original_currency` text,
	`counterparty` text,
	`booking_text` text,
	`description` text,
	`purpose` text,
	`status` text DEFAULT 'unknown' NOT NULL,
	`balance_after_cents` integer,
	`balance_currency` text,
	`country` text,
	`card_last4` text,
	`cardholder` text,
	`note` text,
	`raw_data_json` text NOT NULL,
	`plan_id` text,
	`plan_assignment` text DEFAULT 'none' NOT NULL,
	`budget_id` text,
	`is_archived` integer DEFAULT false NOT NULL,
	`import_seen_count` integer DEFAULT 1 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `import_source`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`first_seen_import_id`) REFERENCES `statement_import`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`last_seen_import_id`) REFERENCES `statement_import`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`plan_id`) REFERENCES `plan`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`budget_id`) REFERENCES `planned_transaction`(`id`) ON UPDATE no action ON DELETE set null
);--> statement-breakpoint
INSERT INTO `bank_transaction__new` (
	`id`,
	`source_id`,
	`first_seen_import_id`,
	`last_seen_import_id`,
	`external_transaction_id`,
	`dedupe_key`,
	`booking_date`,
	`value_date`,
	`amount_cents`,
	`currency`,
	`original_amount_cents`,
	`original_currency`,
	`counterparty`,
	`booking_text`,
	`description`,
	`purpose`,
	`status`,
	`balance_after_cents`,
	`balance_currency`,
	`country`,
	`card_last4`,
	`cardholder`,
	`note`,
	`raw_data_json`,
	`plan_id`,
	`plan_assignment`,
	`budget_id`,
	`is_archived`,
	`import_seen_count`,
	`created_at`,
	`updated_at`
)
SELECT
	`id`,
	`source_id`,
	`first_seen_import_id`,
	`last_seen_import_id`,
	`external_transaction_id`,
	`dedupe_key`,
	`booking_date`,
	`value_date`,
	`amount_cents`,
	`currency`,
	`original_amount_cents`,
	`original_currency`,
	`counterparty`,
	`booking_text`,
	`description`,
	`purpose`,
	`status`,
	`balance_after_cents`,
	`balance_currency`,
	`country`,
	`card_last4`,
	`cardholder`,
	`note`,
	`raw_data_json`,
	`plan_id`,
	`plan_assignment`,
	`budget_id`,
	`is_archived`,
	`import_seen_count`,
	`created_at`,
	`updated_at`
FROM `bank_transaction`;--> statement-breakpoint
DROP TABLE `bank_transaction`;--> statement-breakpoint
ALTER TABLE `bank_transaction__new` RENAME TO `bank_transaction`;--> statement-breakpoint
CREATE UNIQUE INDEX `bankTransaction_sourceId_dedupeKey_idx` ON `bank_transaction` (`source_id`,`dedupe_key`);--> statement-breakpoint
CREATE INDEX `bankTransaction_bookingDate_idx` ON `bank_transaction` (`booking_date`);--> statement-breakpoint
CREATE INDEX `bankTransaction_planId_idx` ON `bank_transaction` (`plan_id`);--> statement-breakpoint
CREATE INDEX `bankTransaction_status_idx` ON `bank_transaction` (`status`);--> statement-breakpoint
CREATE INDEX `bankTransaction_externalTransactionId_idx` ON `bank_transaction` (`external_transaction_id`);--> statement-breakpoint
CREATE INDEX `bankTransaction_isArchived_idx` ON `bank_transaction` (`is_archived`);--> statement-breakpoint
CREATE INDEX `bankTransaction_budgetId_idx` ON `bank_transaction` (`budget_id`);--> statement-breakpoint
PRAGMA foreign_keys=ON;
